var $jscomp=$jscomp||{};$jscomp.scope={};$jscomp.arrayIteratorImpl=function(a){var b=0;return function(){return b<a.length?{done:!1,value:a[b++]}:{done:!0}}};$jscomp.arrayIterator=function(a){return{next:$jscomp.arrayIteratorImpl(a)}};$jscomp.ASSUME_ES5=!1;$jscomp.ASSUME_NO_NATIVE_MAP=!1;$jscomp.ASSUME_NO_NATIVE_SET=!1;$jscomp.SIMPLE_FROUND_POLYFILL=!1;$jscomp.ISOLATE_POLYFILLS=!1;$jscomp.FORCE_POLYFILL_PROMISE=!1;$jscomp.FORCE_POLYFILL_PROMISE_WHEN_NO_UNHANDLED_REJECTION=!1;
$jscomp.defineProperty=$jscomp.ASSUME_ES5||"function"==typeof Object.defineProperties?Object.defineProperty:function(a,b,c){if(a==Array.prototype||a==Object.prototype)return a;a[b]=c.value;return a};$jscomp.getGlobal=function(a){a=["object"==typeof globalThis&&globalThis,a,"object"==typeof window&&window,"object"==typeof self&&self,"object"==typeof global&&global];for(var b=0;b<a.length;++b){var c=a[b];if(c&&c.Math==Math)return c}throw Error("Cannot find global object");};$jscomp.global=$jscomp.getGlobal(this);
$jscomp.IS_SYMBOL_NATIVE="function"===typeof Symbol&&"symbol"===typeof Symbol("x");$jscomp.TRUST_ES6_POLYFILLS=!$jscomp.ISOLATE_POLYFILLS||$jscomp.IS_SYMBOL_NATIVE;$jscomp.polyfills={};$jscomp.propertyToPolyfillSymbol={};$jscomp.POLYFILL_PREFIX="$jscp$";var $jscomp$lookupPolyfilledValue=function(a,b){var c=$jscomp.propertyToPolyfillSymbol[b];if(null==c)return a[b];c=a[c];return void 0!==c?c:a[b]};
$jscomp.polyfill=function(a,b,c,d){b&&($jscomp.ISOLATE_POLYFILLS?$jscomp.polyfillIsolated(a,b,c,d):$jscomp.polyfillUnisolated(a,b,c,d))};$jscomp.polyfillUnisolated=function(a,b,c,d){c=$jscomp.global;a=a.split(".");for(d=0;d<a.length-1;d++){var e=a[d];if(!(e in c))return;c=c[e]}a=a[a.length-1];d=c[a];b=b(d);b!=d&&null!=b&&$jscomp.defineProperty(c,a,{configurable:!0,writable:!0,value:b})};
$jscomp.polyfillIsolated=function(a,b,c,d){var e=a.split(".");a=1===e.length;d=e[0];d=!a&&d in $jscomp.polyfills?$jscomp.polyfills:$jscomp.global;for(var n=0;n<e.length-1;n++){var v=e[n];if(!(v in d))return;d=d[v]}e=e[e.length-1];c=$jscomp.IS_SYMBOL_NATIVE&&"es6"===c?d[e]:null;b=b(c);null!=b&&(a?$jscomp.defineProperty($jscomp.polyfills,e,{configurable:!0,writable:!0,value:b}):b!==c&&(void 0===$jscomp.propertyToPolyfillSymbol[e]&&($jscomp.propertyToPolyfillSymbol[e]=$jscomp.IS_SYMBOL_NATIVE?$jscomp.global.Symbol(e):
$jscomp.POLYFILL_PREFIX+e),$jscomp.defineProperty(d,$jscomp.propertyToPolyfillSymbol[e],{configurable:!0,writable:!0,value:b})))};$jscomp.initSymbol=function(){};
$jscomp.polyfill("Symbol",function(a){if(a)return a;var b=function(e,n){this.$jscomp$symbol$id_=e;$jscomp.defineProperty(this,"description",{configurable:!0,writable:!0,value:n})};b.prototype.toString=function(){return this.$jscomp$symbol$id_};var c=0,d=function(e){if(this instanceof d)throw new TypeError("Symbol is not a constructor");return new b("jscomp_symbol_"+(e||"")+"_"+c++,e)};return d},"es6","es3");
$jscomp.polyfill("Symbol.iterator",function(a){if(a)return a;a=Symbol("Symbol.iterator");for(var b="Array Int8Array Uint8Array Uint8ClampedArray Int16Array Uint16Array Int32Array Uint32Array Float32Array Float64Array".split(" "),c=0;c<b.length;c++){var d=$jscomp.global[b[c]];"function"===typeof d&&"function"!=typeof d.prototype[a]&&$jscomp.defineProperty(d.prototype,a,{configurable:!0,writable:!0,value:function(){return $jscomp.iteratorPrototype($jscomp.arrayIteratorImpl(this))}})}return a},"es6",
"es3");$jscomp.iteratorPrototype=function(a){a={next:a};a[Symbol.iterator]=function(){return this};return a};$jscomp.iteratorFromArray=function(a,b){a instanceof String&&(a+="");var c=0,d=!1,e={next:function(){if(!d&&c<a.length){var n=c++;return{value:b(n,a[n]),done:!1}}d=!0;return{done:!0,value:void 0}}};e[Symbol.iterator]=function(){return e};return e};$jscomp.polyfill("Array.prototype.keys",function(a){return a?a:function(){return $jscomp.iteratorFromArray(this,function(b){return b})}},"es6","es3");
(function(){function a(f,l){f='<select name="'+f+'" style="display:inline-block; width:300px; font-size:15px;height: 30px; border-radius: 15px;padding: 0px 10px; border:1px solid #ccc;">';for(var h=Object.keys(t.codes),g=0;g<h.length;g++)f=l==h[g]?f+('<option value="'+h[g]+'" selected="selected">'+t.codes[h[g]].enName+" ("+t.codes[h[g]].nativeName+")</option>"):f+('<option value="'+h[g]+'">'+t.codes[h[g]].enName+" ("+t.codes[h[g]].nativeName+")</option>");return f}function b(f,l){if(null==l)return f;
f=new URL(f);var h={};if(f.search&&0<f.search.length)for(var g=f.search.substring(1).split("&"),p=0;p<g.length;p++){var k=g[p].split("=");h[decodeURIComponent(k[0])]=decodeURIComponent(k[1])}Object.keys(l).forEach(function(u,B){h[u]=l[u]});var r=[];g=Object.keys(h);g.sort(function(u,B){return u<B?-1:1});g.forEach(function(u,B){r.push(encodeURIComponent(u)+"="+encodeURIComponent(h[u]))});return f.protocol+"//"+f.host+f.pathname+"?"+r.join("&")}var c={ja:'<p>\u30a4\u30f3\u30b9\u30c8\u30fc\u30eb\u3042\u308a\u304c\u3068\u3046\u3054\u3056\u3044\u307e\u3059\u3002</p><p>\u521d\u3081\u306b\u3001<a href="https://www.subtitlesfll.com/privacy_policy" target="_blank">\u30d7\u30e9\u30a4\u30d0\u30b7\u30fc\u30dd\u30ea\u30b7\u30fc\u3001\u5229\u7528\u898f\u7d04</a>\u3092\u304a\u8aad\u307f\u3044\u305f\u3060\u304d\u3001<br>\u540c\u610f\u3057\u3066\u9802\u3051\u307e\u3057\u305f\u3089\u3001\u521d\u671f\u8a2d\u5b9a\u3092\u3057\u3066\u304f\u3060\u3055\u3044\u3002</p>',
"default":'<p>Thank you for installing.</p><p>Please read <a href="https://www.subtitlesfll.com/privacy_policy" target="_blank">Privacy Policy & Terms of Service</a> first.<br>If you agree, please make the initial settings.</p>'},d={ja:"\u3042\u306a\u305f\u306e\u4f7f\u7528\u8a00\u8a9e","default":"Your native language."},e={ja:"\u5b66\u7fd2\u3057\u305f\u3044\u8a00\u8a9e","default":"Your learning language."},n={ja:"\u3042\u308a\u304c\u3068\u3046\u3054\u3056\u3044\u307e\u3057\u305f\u3002\u8a9e\u5b66\u5b66\u7fd2\u3092\u304a\u697d\u3057\u307f\u304f\u3060\u3055\u3044\uff01",
"default":"Thank you!<br>Please enjoy learning language!"},v={ja:"\u5229\u7528\u3059\u308bAmazon","default":"Your Amazon"},z={ja:"\u300c\u4f7f\u7528\u8a00\u8a9e\u300d\u3068\u300c\u5b66\u7fd2\u3057\u305f\u3044\u8a00\u8a9e\u300d\u3092\u540c\u3058\u306b\u3059\u308b\u3053\u3068\u306f\u51fa\u6765\u307e\u305b\u3093\u3002","default":"You can not select the same language."},w={ja:"\u30d7\u30e9\u30a4\u30e0\u30d3\u30c7\u30aa\u306e\u30da\u30fc\u30b8\u3078","default":"Go to Prime Video"},x={ja:"Amazon\u3078\u623b\u308b",
"default":"Back to Amazon"},E={ja:"\u898f\u7d04\u306b\u540c\u610f\u3057\u3001\u4fdd\u5b58","default":"Accept the terms and Save"},m=(window.navigator.languages&&window.navigator.languages[0]||window.navigator.language||window.navigator.userLanguage||window.navigator.browserLanguage).toLowerCase(),y=function(){var f={};if(location.search&&0<location.search.length)for(var l=location.search.substring(1).split("&"),h=0;h<l.length;h++){var g=l[h].split("=");f[decodeURIComponent(g[0])]=decodeURIComponent(g[1])}return f}(),
q=new SubtitlesForLLAmazon,t=new SubtitlesForLLLanguageCode;c=c[m]||c.default;d=d[m]||d.default;e=e[m]||e.default;var G=n[m]||n.default;n=v[m]||v.default;var H=z[m]||z.default,I=w[m]||w.default,J=x[m]||x.default;z=E[m]||E.default;document.getElementById("main_message").innerHTML=c;var F=document.getElementById("amazon_region_selector_container");w='<span style="display:inline-block; width:150px; margin-right:10px; text-align:left;">'+n+"</span>";x=null;y.ref&&(x=(new URL(decodeURIComponent(y.ref))).hostname);
w+=function(f,l){var h='<select name="amazonRegion" style="display:inline-block; width:300px; font-size:15px;height: 30px; border-radius: 15px;padding: 0px 10px; border:1px solid #ccc;">',g=null;if(l&&l!=q.WWW_PRIMEVIDEO_COM)for(var p=0;p<q.hostnames.length;p++)if(q.hostnames[p].hostname==l){g=l;break}null==g&&(g=q.hostnameByBlowserLang(f));q.hostnames.forEach(function(k,r){h=k.hostname==g||r==q.hostnames.length-1&&null==g?h+('<option value="'+k.hostname+'" selected="selected">'+k.country+" - "+k.hostname+
(k.hostname!=k.primeHostname?" ("+k.primeHostname+")":"")+"</option>"):h+('<option value="'+k.hostname+'">'+k.country+" - "+k.hostname+(k.hostname!=k.primeHostname?" ("+k.primeHostname+")":"")+"</option>")});return h}(m,x);F.insertAdjacentHTML("afterbegin",w);m=t.codes[m]?m:t.codes[m.replace(/-.+$/m,"")]?m.replace(/-.+$/m,""):"en";d='<span style="display:inline-block; width:150px; margin-right:10px; text-align:left;">'+d+"</span>"+a("nativeLanguage",m);var C=document.getElementById("native_language_selector_container");
C.innerHTML=d;C.style.cssText="margin:20px;";m='<span style="display:inline-block; width:150px; margin-right:10px; text-align:left;">'+e+"</span>"+a("learningLanguage","en"!=m?"en":"ja");var D=document.getElementById("learning_language_selector_container");D.innerHTML=m;D.style.cssText="margin:20px;";var A=document.getElementById("ok_button");A.innerText=z;A.onclick=function(f){var l=C.getElementsByTagName("select")[0];f=D.getElementsByTagName("select")[0];var h=F.getElementsByTagName("select")[0];
l=l.value;f=f.value;l==f?alert(H):(A.innerText="Please wait...",f={nativeLanguage:l,learningLanguage:f,amazonRegion:h.value},l=chrome.extension.connect({name:"Subtitles for Language Learning (Prime Video)"}),l.onMessage.addListener(function(g){A.remove();g=document.getElementById("contents_container");var p=I;y.ref&&(p=J);if(null==y.ref){var k=h.value;var r=q.getAffiliateId(k);k=q.primeVideoStoreFrontURL(k)+"?tag="+encodeURIComponent(r)}else k=new URL(decodeURIComponent(y.ref)),r=q.getAffiliateId(k.hostname),
k=b(k.href,{tag:r});g.innerHTML='<div style="display:flex; flex-direction:column; width:100%; height:100%;"><div style="display:block; align-items:center; margin:auto;"><p>'+G+'</p></div><div><a class="close_a" href="'+k+'"><div class="close_div" style="padding:0px 20px; display:table-cell; vertical-align:middle; user-select:none;"><span style="">'+p+"</span></div></a></div></div>"}),l.postMessage({type:"installed",configs:f}))}})();
